-- Хранимую процедуру с курсором
USE ConstructionCompanies
GO

DECLARE @HomeName VARCHAR(20)

DECLARE ITCursor CURSOR FOR
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'

OPEN ITCursor
FETCH NEXT FROM ITCursor INTO @HomeName

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @HomeName
FETCH NEXT FROM ITCursor INTO @HomeName END

CLOSE ITCursor
DEALLOCATE ITCursor